In [1]:
mydata = ["Data", 123, True, {"key":"value"}]
print(mydata)

['Data', 123, True, {'key': 'value'}]


In [10]:
import numpy as np

mynumber = np.array([1,2,3,4,5])
print(mynumber)
print(type(mynumber))
print(mynumber.dtype)
print(mynumber.nbytes)

#As number only take 8 bits, change it to make it take less space
mynumber = mynumber.astype(np.int8)
print(mynumber)
print(mynumber.dtype)
print(mynumber.nbytes)

[1 2 3 4 5]
<class 'numpy.ndarray'>
int64
40
[1 2 3 4 5]
int8
5


In [5]:
mymatrix = [[1,2,3], [4,5,6], [7,8,9]]
mymatrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:

mymatrixnp = np.array([[1,2,3], [4,5,6], [7,8,9]])
mymatrixnp  

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])